name: Mirror upstream

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: repo-sync/github-sync@v2
      with:
        source_repo: https://github.com/yushangxiao/pplx2api.git
        source_branch: main
        destination_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
